# -*- coding: utf-8 -*-
"""Untitled100.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqDE9xgHz95RDWDs9mtPVltdArMnxFSP
"""

import pandas as pd

df=pd.read_csv("/content/weatherHistory.csv")

df.head()

df.info()

df.columns

df=df.drop(['Formatted Date','Loud Cover','Daily Summary'],axis=True)

df.head()

df['Summary'].unique()

df=pd.get_dummies(df,drop_first=True,dtype=int)

df.head()

x=df.drop('Temperature (C)',axis=True)
y=df['Temperature (C)']

from sklearn.model_selection import train_test_split,cross_val_score
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeRegressor,plot_tree

dtr=DecisionTreeRegressor( random_state=42)

dtr.fit(x_train,y_train)

y_pred=dtr.predict(x_test)

from sklearn.metrics import mean_squared_error,r2_score

print(mean_squared_error(y_test,y_pred)*100)

print(r2_score(y_test,y_pred)*100)

cross_val_score(dtr,x,y,cv=5,scoring='r2')

import matplotlib.pyplot as plt
plot_tree(dtr,max_depth=6)
plt.show()

import joblib
joblib.dump(dtr, 'decision_tree_weather_model.joblib')

